#!/usr/bin/env python3
"""Rasterize logo_{black,white}.svg into src/logo.h RGBA arrays.

Output pixels carry straight alpha; the bar composites them onto the
live bar_bg at draw time so both variants stay correct under any theme.
"""
import subprocess
import sys

W, H = 18, 19
SVCS = [("logo_black", "black"), ("logo_white", "white")]


def rasterize(path):
    # rsvg for faithful scaling, then supersample down via IMv7; both
    # steps through temp files (magick mishandles rgba:- pipes)
    subprocess.run(["rsvg-convert", "-w", str(W * 4), "-h", str(H * 4),
        "-o", "/tmp/opencode/logo_big.png", path], check=True)
    subprocess.run(["magick", "/tmp/opencode/logo_big.png",
        "-resize", f"{W}x{H}!", "rgba:/tmp/opencode/logo.rgba"],
        capture_output=True, check=True)
    with open("/tmp/opencode/logo.rgba", "rb") as f:
        data = f.read()
    if len(data) != W * H * 4:
        sys.exit(f"unexpected raster size {len(data)}")
    return data


def emit(name, data, fh):
    fh.write(f"static const uint8_t {name}[{W}*{H}*4] = {{\n")
    for row in range(H):
        fh.write("    ")
        for col in range(W):
            px = (row * W + col) * 4
            fh.write(",".join(str(b) for b in data[px:px + 4]) + ",")
        fh.write("\n")
    fh.write("};\n\n")


with open("src/logo.h", "w") as fh:
    fh.write("/* generated by scripts/genlogo.py - do not edit */\n")
    fh.write(f"#define LOGO_W {W}\n#define LOGO_H {H}\n\n")
    for base, _ in SVCS:
        emit(base, rasterize(f"{base}.svg"), fh)
print("src/logo.h written")
